### ISSUE TITLE
Documentation `message.Content` should be `message.content`

### ISSUE THREAD

**Issue by 4x8Matrix** [DiscordLuau/discord-luau#22]
https://discord.com/channels/385151591524597761/1239680678338105476/1285257381776724101

**Comment by CompeyDev** [comment]
why the fuck is it pascal case for a variable

**Comment by CompeyDev** [comment]
Small note: can we not link Discord messages but rather summarize the actual content of the issue? This makes it a lot more clear to someone without being the server itself and is generally good practice.

This should also not be an issue within this PR, but rather in the docs repo, since it is a part of guides, and not any moonwave comments.
